apiVersion: apps/v1
kind: Deployment
metadata: 
  name: postgres-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image : postgres:16.3
          imagePullPolicy: IfNotPresent
          ports: 
            - containerPort: 5432
          # envFrom:
          #   - configMapRef:
          #       name: postgres-secret
          env:
            - name: POSTGRES_USER
              value: app_user
            - name: POSTGRES_PASSWORD
              value: pa$sw0rD!
            - name: POSTGRES_DB
              value: movies
          volumeMounts:
            - mountPath: /var/opt/postgres/data
              name: postgresdb
      volumes:
        - name: postgresdb
          persistentVolumeClaim: 
            claimName: postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-clusterip-srv
  labels: 
    app: postgres
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
    - name: postgres
      protocol: TCP
      port: 5435
      targetPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5435
      targetPort: 5432